version: '2'

volumes:
  nextcloud:
  db:

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    expose:
      - 8080
    links:
      - nextcloud_mariadb
    environment:
      - MYSQL_ADDR=nextcloud_mariadb
      - MYSQL_PASSWORD=<your keycloak mariadb password goes here>
      - PROXY_ADDRESS_FORWARDING=true
      - VIRTUAL_HOST=keycloak.sid
      - VIRTUAL_PORT=8080
    restart: always
  collabora:
    image: collabora/code
    container_name: collabora
    expose:
      - 9980
    extra_hosts:
      - "nextcloud.sid: 192.168.0.185"
    environment:
      - domain=nextcloud\\.sid
      - username=admin
      - password=<your collabora admin password goes here>
      - cert_domain=code.sid
      - VIRTUAL_HOST=code.sid
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
    cap_add:
      - MKNOD
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/docker/nginx/conf.d:/etc/nginx/conf.d
      - /opt/docker/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /etc/ssl/nginx:/etc/nginx/certs
      - /opt/docker/nginx/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    restart: always
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    environment:
      - DEFAULT_HOST=nextcloud.sid
      - HTTPS_METHOD=redirect
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    restart: always
  nextcloud_mariadb:
    image: mariadb
    restart: always
    volumes:
      - /opt/docker/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<your root password goes here>
      - MYSQL_PASSWORD=<your password goes here>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud_mariadb_myadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    links:
      - nextcloud_mariadb:db
    environment:
      - VIRTUAL_HOST=phpmyadmin.sid
    restart: always
  nextcloud_app:
    image: nextcloud
    expose:
      - 80
    links:
      - nextcloud_mariadb
    extra_hosts:
      - "code.sid: 192.168.0.185"
    environment:
      - VIRTUAL_HOST=nextcloud.sid
      - HSTS=max-age=15552000; includeSubDomains; strict-origin
    volumes:
      - /srv/nextcloud_data:/var/www/html/data
      - /opt/docker/nextcloud/config:/var/www/html/config
      - /opt/docker/nextcloud/themes:/var/www/html/themes
      - /opt/docker/nextcloud/custom_apps:/var/www/html/custom_apps
    restart: always
