version: '2'

volumes:
  nextcloud:
  db:

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    expose:
      - 8080
    links:
      - nextcloud_mariadb
    environment:
      - MYSQL_ADDR=nextcloud_mariadb
      - MYSQL_PASSWORD=_ANHvphivkPOU_14Jbe9
      - PROXY_ADDRESS_FORWARDING=true
      - VIRTUAL_HOST=keycloak.sid-owncloud
      - VIRTUAL_PORT=8080
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/docker/nginx/conf.d:/etc/nginx/conf.d
      - /opt/docker/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /etc/ssl/nginx:/etc/nginx/certs
    restart: always
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    environment:
      - DEFAULT_HOST=sid-owncloud
      - HTTPS_METHOD=redirect
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    restart: always
  nextcloud_mariadb:
    image: mariadb
    restart: always
    volumes:
      - /opt/docker/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${replaceme}
      - MYSQL_PASSWORD=${replaceme}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud_mariadb_myadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    links:
      - nextcloud_mariadb:db
    environment:
      - VIRTUAL_HOST=phpmyadmin.sid-owncloud
    restart: always
  nextcloud_app:
    image: nextcloud
    expose:
      - 80
    links:
      - nextcloud_mariadb
    environment:
      - VIRTUAL_HOST=sid-owncloud
    volumes:
      - /srv/owncloud_data:/var/www/html/data
      - /opt/docker/nextcloud/config:/var/www/html/config
      - /opt/docker/nextcloud/themes:/var/www/html/themes
      - /opt/docker/nextcloud/custom_apps:/var/www/html/custom_apps
    restart: always
